### ISSUE TITLE
Add upcoming events to home page

### ISSUE THREAD

**Issue by tomhohenstein** [Boston-Open-Researcher-Group/BORG#1]
It would be great if we had the next upcoming event on the homepage.

**Comment by Kevin-Mattheus-Moerman** [comment]
Done. They are rendered as "cards" on the [home page](https://boston-open-researcher-group.github.io/BORG/). The event markdown file contains yml fields which now also specify an "expiration_data" for the event. All upcoming events (events that are not expired/over) will be rendered on the home page.
