### ISSUE TITLE
Issues with forking

### ISSUE THREAD

**Issue by wkearn** [Boston-Open-Researcher-Group/BORG#3]
Since this website is technically a fork of the Study Group websites, there are a few issues that we run into.

1. We can't search through code in this repository.
2. Forking is a little weird since you're technically forking from mozillascience. For instance, I can't fork the BORG website separately because I already have a fork for the BU Study Group. That's not a huge deal for me because I'm a member of the BORG organization and can edit things in this repo, but this might make it tricky for someone else to contribute.

It may be more trouble than it is worth to de-fork this from the Study Group page: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

But I just wanted to ask if this is something we should do.

**Comment by wkearn** [comment]
Also, pull requests get submitted by default to mozillascience and not to the BORG.

**Comment by tomhohenstein** [comment]
The PR issue might make the process worth while. Defiantly something to think about. Could we also just delete the repo (obviously with a backup) and make a new one without the connection? Could be easier than contacting GitHub

**Comment by Kevin-Mattheus-Moerman** [comment]
I contacted GitHub before to decouple a fork/remove the fork link. They did it within a day so it was super easy fast.
